# /mnt/work/kaya/main-srv/db-srv/configs/docker-compose.yml

services:
  postgres_db:
    image: postgres:18.1-trixie
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # временно, для упрощения
    volumes:
      - postgres_nvme_data:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "5432:5432"
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  qdrant: 
    image: qdrant/qdrant:latest 
    container_name: qdrant_db
    restart: unless-stopped 
    volumes: 
      - /mnt/data_bases/qdrant_data:/qdrant/storage 
      - /mnt/data_bases/qdrant_snapshots:/qdrant/snapshots
      - /mnt/work/kaya/db-srv/configs/qdrant_config.yaml:/qdrant/config/production.yaml 
    ports: 
      - "6333:6333" 
      - "6334:6334" 

volumes:
  postgres_nvme_data:
    external: true
